### ISSUE TITLE
Team - Insight Research - Post-interview debrief

### ISSUE THREAD

**Issue by iamjoshfrank** [revelry-foundation/nightingale#12]
## Background
After we have conducted our interview, the interviewer and note-taker should discuss surprises and reflect on what they heard, then place their notes in the Discovery folder on the [project google drive](https://drive.google.com/drive/folders/18e5LHV2LyPUshdBdnfxe_9M4WEZ6Ms7K)

## Scenario: Team members debrief after an interview
- [ ] When I have conducted an interview #27 
- [ ] Then I conduct the post-interview debrief
	- [ ] Engage the team (interviewer and note-taker) in a post-interview debrief to discuss surprises and reflect on what you heard
	- [ ] Add additional any additional notes based on discussion if needed
	- [ ] Open the Discovery Folder in [project google drive](https://drive.google.com/drive/folders/18e5LHV2LyPUshdBdnfxe_9M4WEZ6Ms7K)
	- [ ] Create a Folder for the interviewee's name 
	- [ ] Upload recording of the interview to folder
	- [ ] upload notes to the folder
	- [ ] If you promised the participant any follow-up communications, identify who will send them and when
	- [ ] Consider updating the interview guide based on this interview [here](https://github.com/revelry-foundation/nightingale/issues/10#issuecomment-634211734)
- [ ] And I move on to #34 to create a Validation Board

**Comment by alinelea** [comment]
Dr Danielle Thomas interview notes: https://docs.google.com/document/d/1cqLblhTksuQ4vovPjJFTBd_p0ccdpSHeHau-6WC25DI/edit?usp=sharing working on the debrief with @HauwaAguillard now, but we also have another interview coming up at 2pm shortly.

**Comment by alinelea** [comment]
Posting the key takeaways from the two interviews @HauwaAguillard and I conducted today in order to shine on light on these nuggets for the entire Nightingale team. 

## [Dr. Danielle Thomas Interview](https://docs.google.com/document/d/1cqLblhTksuQ4vovPjJFTBd_p0ccdpSHeHau-6WC25DI/edit) Key Takeaways 
**About the interviewee and their role in their community** 
- Dr. Danielle Thomas got her Masters and PhD at LSU in Sociology from 2010-2016. She then worked full-time for a nonprofit sending kids on mission trips. She is now an adjunct professor in sociology at LSU, and works at Renew Church doing community outreach. 
- She’s heavily involved in the Gardere community with their youth sports teams, summer camp, and food assistance programs. She currently spends 10-15 hours/week delivering meals from the schools to the homes of children. 

**What are you hearing from the community as it relates to COVID-19?**
- People are overwhelmed and unsure of who to trust. They consume their news via social media on their smartphones. Most don’t have cable to watch the news, plus their first language is Spanish and there’s no local news in Spanish. Lots of disinformation. 
- She has talked to teenagers who didn’t understand why their school had to be closed and what being asymptomatic meant. Thankfully, the virus hasn’t hit their community hard, so it’s hard for them to understand something they are not witnessing firsthand. 

**Current outreach efforts**
- Dr. Thomas and other volunteers deliver food from the schools to the homes of kids each day. They also place flyers in the food bags to provide accurate and trustworthy information to the families. 
- Dr. Murielle Harrison (PhD in Psych at Southern University) is focused on substance abuse prevention and health. She was concerned about how people were getting their info, so she started putting flyers in food delivery bags with the proper info they need to know. Example: kids can apply for a $300 check to reimburse them for losing school time. She has people on her team who speak Spanish and can translate the info for the flyers. 
- Dr. Harrison also has a list of community leaders that she emails periodically, so they can filter down the info to their families and communities. 

**Best ways to reach at risk communities**
- Find community leaders/people others trust and give them the information to disseminate. Some leaders include: leaders of the Hispanic church, Dr. Harrison, Darren Fontenot, the director of the youth sports program. Plus, smaller churches and people others trust. Example, there’s a “candy man” who runs an underground convenience store from his house. People stop in to buy essentials and snacks. Leave info with him and if he trusts it. 
- Targeted social media advertising. So many people are using social media with the parents on Facebook and the kids on Instagram and Snapchat. 
- They’re not paying attention to the governors’ announcements or watching the news.

**The critical needs they're hearing from the at risk community**
- Childcare. Many parents are essential workers (grocery, restaurant workers), so they had to start leaving the kids home alone when the school closed. 
- Feeding kids. Parents were also not used to giving their kids breakfast or lunch since the school and state provided it. The parents are also unable to drive to the school to pick up the food, so it daily. 
- Job creation. If they weren’t essential, then they lost their job. Those working in “informal” jobs like cutting grass or cleaning homes lost work due to those that used to hire them losing their jobs. 
- Youth services. Parents are unsure what Phase 2-3 will look like and how that will impact summer programs. Many summer programs are waiting to hear more news before making decisions about shifting their programs from indoors to outdoors. 

**Thoughts and potential resistance to contact tracing? Ways to gain their community’s trust around contact tracing**
- Dr. Thomas personally believes that contact tracing will be really important as we open up the state. 
- However, there will lots of suspicion from her community stemming from the already so much misinformation. Many community members are undocumented, so they will be resistant to signing up for an app with their info. 
- She suggests limiting the app to ask for only pieces of info we absolutely need to be as least invasive as possible. For example, can we collect initials and not names? 
- Get the community leaders involved and they can communicate it. 
- Hire people to be contact tracers in the community to create jobs. People would appreciate the income from a company that shows they care about supporting the local community. 
- Even young people can do that kind of work since 18-20-year-olds are tech-savvy and social. Have a contest where the kids make videos of themselves explaining contact tracing then submit them and the winners can be used as actual ads. 
- Leverage the public school systems to get students studying code and design to get involved and help build the app. 

## [Michael A.V. Interview](https://docs.google.com/document/d/1_uDvtYnVUdSPHPLsR5A7SenGuc7iodYZzIl4RqYREJ4/edit) Key Takeaways 
**About the interviewee and their role in their community** 
- Michael A.V. Mitchell is a Community Engagement Specialist, motivational speaker and rap artist based in Baton Rouge. He also founded Business Solutions Company where he partners with businesses to connect them to the community via planned events. He also works with businesses on how to optimize their workforce. He is regarded as a community influencer and is often invited to speak at schools, events, political settings, etc. 

**What are you hearing from the community as it relates to COVID-19**
- At the beginning of the pandemic, there was an outcry from the African-American community for more testing. That request has since been fulfilled from various organizations and companies. Now, folks want to go back to work but have differing opinions on how and when. 
- For example, he recently held a call with 120 barbers and stylists and the mayor to talk about reopening barbershops and salons. Some wanted to go ahead and reopen while others were more cautious and did not want to yet. There is also a partnership from the mayor’s office to provide thermometers to barbershops and salons. 
- People are afraid of the numbers spiking again. He mentioned that commercial testing sites’ numbers do not align with what governmental health agencies are reporting and this causes frequent distrust. 

**Current outreach efforts**
- He uses his own platforms to disseminate information. He recently interviewed the mayor of Baton Rouge and Chief of Police of Baton Rouge about the Covid situation. 
- He referenced the mayor’s Facebook page as a trustworthy source. 

**Best ways to reach at risk communities**
- Segmented marketing. Some folks are on Facebook and Instagram but not all. Some go to church and others don’t. So the message needs to be spread by various mediums and from various community leaders in order to reach everyone. He suggested finding any trusted person who has a platform, get their buy-in and let them communicate with their community and audience. 

**The critical needs they're hearing from the at risk community**
- Financial resources: 
  - Unemployment benefits. Some were successful and some were not. 
  - PPP business loans. He knows several business owners who applied for the PPP loan but were not accepted in time. More were not successful than the ones who were. Some didn’t even know the program existed. He himself was told by the bank that he was on a long waiting list since he went online first and not directly to a bank. 
- Kids out of school (didn’t elaborate) 
- Access to correct, credible information. Filtering through information to determine which is accurate. Many do not trust the president and this causes confusion since they can’t trust the person they should be able to trust the most. They also have smartphones, so they do their own research. However, how do you decipher between a trustworthy news source or website and one that isn’t? Many people watch the Governor’s daily announcement with the numbers and the local 6 o’clock news. 

**Thoughts and potential resistance to contact tracing? Ways to gain their community’s trust around contact tracing**  
- Not understanding how contact tracing works. Educating the community will be key. Some may be wary of their phones tracking them, but would likely buy-in if you fully explained the process and privacy with notifications on their phones. He hadn’t heard any objections to the manual contact tracing by phone. 
- He suggested gamification and incentivizing the contact tracers or people to input their info. Have community leaders be the contact tracers. 
- He suggested circulating surveys around the community to gauge interest and knowledge of contact tracing.  
- Keep the technology simple and direct. Bottom up vs top down. Let (tech-savvy) the kids lead. 
- For example, he created a rap music video about destigmatizing HIV/AIDs.

**Comment by Mcscott142** [comment]
Chris O'Shea notes and recording is [here](https://docs.google.com/document/d/1xDzjEtTUJ8xgd6Id2J6j60aHu2nqS_hBLjjQ2ub8ad8/edit#). Sent him a follow-up email as well. It sounds like he may have some great contacts that might want to get involved.

**Comment by HauwaAguillard** [comment]
Sent a follow-up/ thank you email to research participants
