### ISSUE TITLE
Team - Insight Research - Review Interview Notes, Synthesize Findings

### ISSUE THREAD

**Issue by iamjoshfrank** [revelry-foundation/nightingale#13]
### Background
- [x] [Frame design challenge question](https://github.com/revelry-foundation/nightingale/issues/25)
- [x] [Identify customer pool](https://github.com/revelry-foundation/nightingale/issues/8)
- [x] [Reach out and schedule customer interview](https://github.com/revelry-foundation/nightingale/issues/9)
- [x] [Conduct customer interview](https://github.com/revelry-foundation/nightingale/issues/10)
- [x] [Conduct Interviews w/ Notes and Recordings](https://github.com/revelry-foundation/nightingale/issues/12) 

### When
- [ ] [Create new validation board from this template](https://docs.google.com/spreadsheets/d/1ih9t6cCNgddM-vwEediRvrWp7QaZ1DbxvVQ1FqEWzkM/edit?usp=sharing). Copy and fill anew
- [ ] List Core Assumptions from interview into your new validation board
- Your problem and ideas about how to solve it are based on a set of assumptions. Lean product design is all about surfacing and testing those assumptions. Before diving into deciding what to test (building hypotheses), it’s important to consider all of your project’s potential assumptions.

- [ ] List Riskiest Assumptions from interview into your new validation board
Which core assumption(s) has the highest level of uncertainty that we'll quickly want to validate?

### Then
- [ ] As a team create a single validation board
    - [ ] Team members share their interview findings/assumptions thus far
    - [ ] Consolidate riskiest and core assumptions into one validation board
    - [ ] Write a problem statement
    - [ ] Develop broad hypotheses
    - [ ] Prioritize broad hypotheses
    - [ ] Break down hypotheses
- [ ] As a team use validation board to Run Design Studio
