### ISSUE TITLE
Team Member - Discovery Research - Frame a question

### ISSUE THREAD

**Issue by jeremybrady** [revelry-foundation/nightingale#25]
### Background
Develop a contact tracing tool directed by Louisiana Department of Public Health

### When
- [x] Frame the design challenge as question using [the five whys](https://en.wikipedia.org/wiki/Five_whys)
_"How might we [insert problem] for [[audience/proto-persona](https://uxdesign.cc/ux-creating-proto-personas-76a1738401a2)] so that they can [perform action that solves for the problem]?"_

### Then
- [x] [Frame design challenge question](https://github.com/revelry-foundation/nightingale/issues/25)

##### Planning and Recruitment [Milestone](https://github.com/revelry-foundation/nightingale/milestone/5)
- [x] [Identify customer pool](https://github.com/revelry-foundation/nightingale/issues/8)
- [x] [Reach out and schedule customer interview](https://github.com/revelry-foundation/nightingale/issues/9)
- [x] [Develop Interview Script](https://github.com/revelry-foundation/nightingale/issues/10)
- [x] [Create a Place for Interview Notes, Recordings](https://github.com/revelry-foundation/nightingale/issues/11) 

##### Conduct Discovery [Milestone](https://github.com/revelry-foundation/nightingale/milestone/6) 
- [x] [Conduct customer interview](https://github.com/revelry-foundation/nightingale/issues/25)
- [x] [Post-interview debrief](https://github.com/revelry-foundation/nightingale/issues/12) 
- [x] [Create new validation board from this template](https://docs.google.com/spreadsheets/d/1ih9t6cCNgddM-vwEediRvrWp7QaZ1DbxvVQ1FqEWzkM/edit?usp=sharing). Copy and fill a new one #34 
- [x] List [Core Assumptions](https://docs.google.com/spreadsheets/d/1ih9t6cCNgddM-vwEediRvrWp7QaZ1DbxvVQ1FqEWzkM/edit#gid=0) from interview into your new validation board #34 
- [x] List [Riskiest Assumptions](https://docs.google.com/spreadsheets/d/1ih9t6cCNgddM-vwEediRvrWp7QaZ1DbxvVQ1FqEWzkM/edit#gid=0) from interview into your new validation board #34 
- [x] As a team consolidate riskiest and core assumptions into one validation board
   - [x] As a team write a problem statement

**Decide—Elaborate on research from your Discovery phase to guide design/dev efforts**
- [x] [As a team Develop broad hypotheses](https://docs.google.com/spreadsheets/d/1ih9t6cCNgddM-vwEediRvrWp7QaZ1DbxvVQ1FqEWzkM/edit#gid=0)
- [x] [As a team Prioritize broad hypotheses](https://docs.google.com/spreadsheets/d/1ih9t6cCNgddM-vwEediRvrWp7QaZ1DbxvVQ1FqEWzkM/edit#gid=0)
- [x] [As a team Run Design Studio](https://github.com/revelry-foundation/nightingale/issues/25#issue-625222121)
- [x] [Plan sprint](https://github.com/revelry-foundation/nightingale/issues/15#issuecomment-636137521)
- [x] As a team Run Sprint against prioritized MVP to Develop and stand-up MVP that can be tested

**Comment by jeremybrady** [comment]
_"How might we identify and enable through the direction of public health officials, trusted contact tracers within the community with the means to securely and anonymously identify those with COVID-19?"_

**Comment by iamjoshfrank** [comment]
I'm really unclear about the reason for this Issue. I have a hard time processing the use of **When** and **Then** in this context, or at least with the words that are attached to them.

Is this a meta-tracking Issue to track a bunch of different Issues (that appear to already be organized into their own Milestones? If so, then my suggestion for the future is to reduce complexity and rely on the Milestones to do the heavy lifting.

Can we close this? Or do you still need it for tracking:

> - [ ] As a team Run Design Studio
> - [ ] As a team Run Sprint to Develop and stand-up MVP that can be tested

I'd argue those things have (or will have) their own Issues and/or Milestones; and I'd rather not have a meta-tracking Issue like this hanging out in the `Write` column on the Kanban for days / a week+. In any case, if this Issue stays open, let's find a better home than the `Write` column.

**Comment by jeremybrady** [comment]
@iamjoshfrank Index to document the process giving a transparent look into the why, so we can create a playbook against this—empowering other teams to model this.

When we're done, we'll close it.
