### ISSUE TITLE
Discovery Round 2 — Contact Tracing App Brief

### ISSUE THREAD

**Issue by jeremybrady** [revelry-foundation/nightingale#91]
### Background
Develop a contact tracing tool directed by Louisiana Department of Public Health

### When
- [x] Frame the design challenge as question using [the five whys](https://en.wikipedia.org/wiki/Five_whys)
_"How might we [insert problem] for [[audience/proto-persona](https://uxdesign.cc/ux-creating-proto-personas-76a1738401a2)] so that they can [perform action that solves for the problem]?"_

### Then
- [x] Frame design challenge question
_"How might we best promote and create adoption for a COVID-19 tracing app, for [students](https://docs.google.com/document/d/18d0H8DJVMhMUNkVN_nVcd4BO8SXt8zpNAkHJJwAIGq0/edit?usp=sharing) returning to Louisiana state Universities in the fall?"_

##### Planning and Recruitment [Milestone](https://github.com/revelry-foundation/nightingale/milestone/5)
- [ ] [Identify customer pool](https://github.com/revelry-foundation/nightingale/issues/90)
- [ ] [Reach out and schedule customer interview](https://github.com/revelry-foundation/nightingale/issues/89)
- [ ] [Develop Interview Script](https://github.com/revelry-foundation/nightingale/issues/88)
- [ ] [Create a Place for Interview Notes, Recordings](https://github.com/revelry-foundation/nightingale/issues/87) 

##### Conduct Discovery
- [ ] [Conduct customer interview](https://github.com/revelry-foundation/nightingale/issues/88)
- [ ] [Post-interview debrief](https://github.com/revelry-foundation/nightingale/issues/86) 
- [ ] [Create new validation board from this template](https://docs.google.com/spreadsheets/d/1wvH6H-EJHnQDN-ye-iFH4GRMgoxt84LXB0kurlfCcn0/edit?usp=sharing). 
- [ ] List [Core Assumptions](https://docs.google.com/spreadsheets/d/1wvH6H-EJHnQDN-ye-iFH4GRMgoxt84LXB0kurlfCcn0/edit?usp=sharing) from interview into your new validation board 
- [ ] List [Riskiest Assumptions](https://docs.google.com/spreadsheets/d/1wvH6H-EJHnQDN-ye-iFH4GRMgoxt84LXB0kurlfCcn0/edit?usp=sharing) from interview into your new validation board
- [ ] As a team consolidate riskiest and core assumptions into one validation board
   - [ ] As a team write a problem statement

**Decide—Elaborate on research from your Discovery phase to guide design/dev efforts**
- [ ] [As a team Develop broad hypotheses](https://docs.google.com/spreadsheets/d/1wvH6H-EJHnQDN-ye-iFH4GRMgoxt84LXB0kurlfCcn0/edit?usp=sharing)
- [ ] [As a team Prioritize broad hypotheses](https://docs.google.com/spreadsheets/d/1wvH6H-EJHnQDN-ye-iFH4GRMgoxt84LXB0kurlfCcn0/edit?usp=sharing)
- [ ] As a team Run Design Studio
- [ ] Share results back with state
